name: 🚫 Won't Fix
description: This will not be worked on
title: "[WONTFIX]: "
labels: ["wontfix"]
body:
  - type: markdown
    attributes:
      value: |
        This category is primarily for maintainers. If you're a contributor and believe something shouldn't be fixed, please explain why.
  - type: textarea
    id: issue
    attributes:
      label: Related Issue
      description: If it exists, provide a link to the original issue
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Explain why you believe this should not be fixed
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Are there any alternatives or workarounds?
